name: Test and Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 19.x
        uses: actions/setup-node@v4
        with:
          node-version: 19
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}
      - name: Build and push Docker image
        id: docker_push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }}
  deploy:
    needs: build
    environment:
      name: deploy-prod
      url: http://bmw.yixi.pro/
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          port: 22
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd $HOME
            docker rm -f bmw-frontend || true
            docker container run -d --name bmw-frontend --restart=always -p 8800:80 ${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }}
